### ISSUE TITLE
Umbrella Issue: CNCF Tech Doc Recommendations

### ISSUE THREAD

**Issue by jbogarthyde** [in-toto/in-toto.io#46]
*UPDATE 05/27/2024 (transfer sub-issues, update issue description)*
 

# Umbrella issue
This is a checklist for the CNCF technical documentation analysis and implementation plan. It should be updated as sub-issues are added, completed, or otherwise modified. All related Issues should be given the Documentation label.

This issue tracks recommended changes resulting from an analysis of the in-toto documentation commissioned by CNCF.  
- The CNCF in-toto documentation effort is tracked in the CNCF Tech Docs repo: https://github.com/cncf/techdocs/pull/200
- For a more detailed description, see [analysis and supporting documents](https://github.com/cncf/techdocs/blob/main/assessments/0009-in-toto/README.md).   

The goal for these changes is to develop web-based documentation aimed explicitly at users, and distinguish the user documentation from the documentation intended for contributors. 

There are three distinct audiences for user documentation that require introductory information at different levels of detail: 
- A basic intro suitable for *evaluators and potential adopters* is already linked directly from the [home page About tab](https://in-toto.io/in-toto/). 
- The mid-level overview in https://github.com/in-toto/in-toto/blob/develop/README.md is aimed specifically at *users* - that is, adopters who are integrating an implementation into their own workflows, and the project owners who will create layouts.
- The low-level, comprehensive technical overview in the [in-toto Technical Specification](https://github.com/in-toto/docs/blob/v1.0/in-toto-spec.md#1-introduction) is primarily aimed at *contributors*.  

## User doc sub-issues

This is a list of issues representing the recommended work on the in-toto website and technical documentation for users. 

### Create home page for user documentation on website

To be immediately useful, the landing page should provide a top-level roadmap to [existing docs](https://github.com/cncf/techdocs/blob/main/assessments/0009-in-toto/survey-of-existing-doc.md). This is a necessary step in raising the maturity level of this project.

~The landing page URL for the [read-the-docs site](https://in-toto.readthedocs.io/en/latest/) currently hosts the auto-generated Python reference doc. To use Read the Docs as the site generator, expand and repurpose this URL as the new overall Doc Home Page, add user-doc build files in user-doc source directory, and modify the destination for the reference-doc build.~

-  [ ] https://github.com/in-toto/in-toto.io/issues/34    

### Expose new-user information on website

Information that is needed by new users is currently in GitHub readme files and in the Specification. Adapt and move the information to source files for the web-based documentation.

- [ ] https://github.com/in-toto/in-toto.io/issues/35

- [ ] https://github.com/in-toto/in-toto.io/issues/36
      Copy sections of the in-toto Technical Specification into source for a system overview page.
   
- [ ] https://github.com/in-toto/in-toto.io/issues/37 

## Contributor doc sub-issues

This is a list of issues representing the recommended work on supporting contributions to documentation. Contributor policies for documentation can remain in GitHub, in the  https://github.com/in-toto/community repo. 
See https://github.com/in-toto/community/issues/9

- [ ]  https://github.com/in-toto/community/issues/28
- [ ]  https://github.com/in-toto/in-toto/issues/755
 
- [ ]  https://github.com/in-toto/community/issues/30
The policy for contributing to user documentation specifies how and where to make additions and changes to existing user documentation.
